### ISSUE TITLE
Installing on Heroku

### ISSUE THREAD

**Issue by ianseyer** [mozilla/popcorn.webmaker.org#614]
Hi there.

Having issues getting popcorn working properly on Heroku.

It detects the node buildpack, and proceeds to install, but hits an error while installing `node-gyp rebuild`, which apparently is being executed by `node-expat` which is something that never actually appears in `/node_modules` so I am having difficulty tracking it down. The error is too far back in my error logs to retrieve, but was basically a version compatibility error as described roughly here: https://github.com/hipchat/hubot-hipchat/issues/232

I have, however, been able to surpass this by altering my node version to use 0.10 and reverting to v63 of the Heroku Node buildpack (as described in the above issue).

This successfully deploys me a web interface, which can be seen here: https://webmakerpopcorn.herokuapp.com. It can pull media (except youtube, unless I'm misunderstanding something) successfully. However, I cannot seem to login through either a Persona or a username.

In my Heroku error logs I can see:
`POST /authenticate 500 11ms - 56b`
and
`POST /auth/v2/uid-exists 500 4ms - 56b` 
respectively.

How would one go about successfully deploying on Heroku?

ps, my local.js configuration file: https://gist.github.com/ianseyer/c0022ace57cbf458cd9d

**Comment by secretrobotron** [comment]
@jbuck @Pomax any advice you can give here?

**Comment by Pomax** [comment]
I suspect this is an old dependency relying on a pre-node v12 node-expat. Rather than downgrading to node 10, it's probably worth checking which node_module has the node-expat dependency and then `npm uninstall that --save` and re`npm install that --save`, to see if it gets it to node 12 compliance.

**Comment by ianseyer** [comment]
Hmm.

@Pomax upon your advice, I tracked down the issue to xml2json. I uninstalled & reinstalled and saved it to package.json (which now reflects the latest version of xml2json).

Nothing seems to have changed. 

Here is the full stack trace: https://gist.github.com/ianseyer/3b5e028c96fd330bcf0b

**Comment by Pomax** [comment]
fun fact: heroku does support sqlite, but because the dyno resets the FS on a sleep/wake cycle, nothing you save is actually persistent (so you indeed need some SQL addon instead if you need persistent data).

If you want to file a PR for that bumped webmaker-download-locales, I'd be happy to merge it in. I think it stopped using xml2json around 0.2 -- should have remember that, since it completely screwed up windows testing at the time so I was actually the person to file the issue on that

**Comment by ianseyer** [comment]
Done! Will be creating more issues, as I have found quite a few that seem to have simple solutions.

**Comment by Pomax** [comment]
:+1:
